# Makefile for cocotb DFF example

# defaults
SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += dff.v
TOPLEVEL = dff

MODULE = test_dff

include $(shell cocotb-config --makefiles)/Makefile.sim
